
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "beam"

[env]
TERM = "alacritty"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 8
y = 8

[general]
live_config_reload = true
import = ["colors.toml", "fonts.toml"]
