[colors.bright]
black = "#555555"
blue = "#9922AB"
cyan = "#2980b9"
green = "#307843"
magenta = "#ff79c6"
red = "#aa2227"
white = "#ffffff"
yellow = "#f1fa8c"

[colors.normal]
black = "#000000"
blue = "#9922AB"
cyan = "#2980b9"
green = "#307843"
magenta = "#ff79c6"
red = "#aa2227"
white = "#7f8c8d"
yellow = "#f1fa8c"

[colors.primary]
background = "#1b1b1d"
foreground = "#fcfdfd"
